---
- name: Check system authentication configuration
  check_mode: true
  ansible.builtin.lineinfile:
    state: absent
    path: /etc/pam.d/system-auth
    regexp: '^auth.*pam_sss.so.*'
  register: auth_config
  changed_when: false

- name: Create Kerberos configuration file
  ansible.builtin.template:
    src: "{{ domain_ad_krb5_config_file | default('krb5.conf.j2', true) }}"
    dest: /etc/krb5.conf.d/zz-ansible.conf
    mode: '0644'
  register: krb5_config

- name: Create SSSD configuration file
  ansible.builtin.template:
    src: "{{ domain_ad_sssd_config_file | default('sssd.conf.j2', true) }}"
    dest: /etc/sssd/conf.d/zz-ansible.conf
    mode: '0600'
  register: sssd_config

- name: Run SSSD configuration check
  check_mode: false
  ansible.builtin.command: sssctl config-check
  changed_when: false
  when: "'sssd' in ansible_facts.packages"

- name: Join AD domain
  no_log: true
  ansible.builtin.shell: >
    set -o pipefail ;
    echo '{{ domain_ad_admin_password }}' |
    adcli -v join
    --domain={{ domain_ad_domain }}
    --host-fqdn={{ ansible_facts.fqdn }}
    --login-user={{ domain_ad_admin_username }}
    --stdin-password
  changed_when: true
  when: not krb5_keytab.stat.exists

- name: Enable oddjobd service
  ansible.builtin.service:
    name: oddjobd
    enabled: true
  when: "'oddjob-mkhomedir' in ansible_facts.packages"

- name: Start oddjobd service
  ansible.builtin.service:
    name: oddjobd
    state: started
  when: "'oddjob-mkhomedir' in ansible_facts.packages"

- name: Enable sssd-kcm socket
  ansible.builtin.service:
    name: sssd-kcm.socket
    enabled: true
  when: "'sssd-kcm' in ansible_facts.packages"

- name: Enable sssd service
  ansible.builtin.service:
    name: sssd
    enabled: true
  when: "'sssd' in ansible_facts.packages"

- name: Start sssd service
  ansible.builtin.service:
    name: sssd
    state: started
  register: service_start
  when: "'sssd' in ansible_facts.packages"

- name: Restart sssd to apply configuration changes
  ansible.builtin.service:
    name: sssd
    state: restarted
  when:
    - "'sssd' in ansible_facts.packages"
    - service_start is not changed
    - not krb5_keytab.stat.exists or
      krb5_config is changed or
      sssd_config is changed

- name: Configure system-wide authentication
  ansible.builtin.command: authselect select -f sssd {{ domain_ad_auth_select_parameters }}
  changed_when: true
  when:
    - domain_ad_auth_config_update | bool
    - auth_config.found == 0
