---
galaxy_info:
  role_name: performance_tuning
  author: Marko Myllynen <myllynen@redhat.com>
  company: Red Hat, Inc.
  description: performance_tuning role
  license: GPLv3+
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - rhel
    - centos
    - configuration
dependencies: []
