---
- name: Disable system runtime watchdog configuration
  vars:
    option_value: "{{ 'off' if ansible_facts.distribution_major_version | int >= 9 else '0' }}"
  ansible.builtin.lineinfile:
    path: "{{ watchdog_conf }}"
    regexp: '^(#|)RuntimeWatchdogSec=.*'
    line: '#RuntimeWatchdogSec={{ option_value }}'
  register: watchdog_runtime
  when: watchdog_check.stat.exists

- name: Restore system reboot watchdog default configuration
  vars:
    option_name: "{{ 'RebootWatchdogSec' if ansible_facts.distribution_major_version | int >= 9 else 'ShutdownWatchdogSec' }}"
  ansible.builtin.lineinfile:
    path: "{{ watchdog_conf }}"
    regexp: '^(#|){{ option_name }}=.*'
    line: '#{{ option_name }}=10min'
  register: watchdog_reboot
  when: watchdog_check.stat.exists

- name: Disable system kexec watchdog configuration
  vars:
    option_state: "{{ 'present' if ansible_facts.distribution_major_version | int >= 9 else 'absent' }}"
  ansible.builtin.lineinfile:
    state: "{{ option_state }}"
    path: "{{ watchdog_conf }}"
    regexp: '^(#|)KExecWatchdogSec=.*'
    line: '#KExecWatchdogSec=off'
  register: watchdog_kexec
  when: watchdog_check.stat.exists

- name: Restore system watchdog device default configuration
  vars:
    option_state: "{{ 'present' if ansible_facts.distribution_major_version | int >= 9 else 'absent' }}"
  ansible.builtin.lineinfile:
    state: "{{ option_state }}"
    path: "{{ watchdog_conf }}"
    regexp: '^(#|)WatchdogDevice=.*'
    line: '#WatchdogDevice='
  register: watchdog_device
  when: watchdog_check.stat.exists

- name: Reload systemd to apply configuration changes
  ansible.builtin.systemd:
    daemon_reload: true
  when: watchdog_runtime is changed or
        watchdog_reboot is changed or
        watchdog_kexec is changed or
        watchdog_device is changed

- name: Rebuild initramfs
  ansible.builtin.command: dracut -f --regenerate-all
  changed_when: true
  when: watchdog_runtime is changed or
        watchdog_reboot is changed or
        watchdog_kexec is changed or
        watchdog_device is changed
