---
- name: Gather needed facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Set watchdog configuration file
  ansible.builtin.set_fact:
    watchdog_conf: "{{ '/etc/systemd/system.conf.d/95-ansible.conf'
                       if ansible_facts.distribution_major_version | int >= 10 else '/etc/systemd/system.conf' }}"

- name: Check watchdog configuration file
  ansible.builtin.stat:
    path: "{{ watchdog_conf }}"
  register: watchdog_check

- name: Enable system watchdog
  ansible.builtin.include_tasks: enable.yml
  when: watchdog_enable | bool

- name: Disable system watchdog
  ansible.builtin.include_tasks: disable.yml
  when: not watchdog_enable | bool
