---
- name: Gather package facts
  ansible.builtin.package_facts:

- name: Disable usbguard service
  ansible.builtin.service:
    name: usbguard
    enabled: false
  when: "'usbguard' in ansible_facts.packages"

- name: Stop usbguard service
  ansible.builtin.service:
    name: usbguard
    state: stopped
  when: "'usbguard' in ansible_facts.packages"
