---
- name: Gather package facts
  package_facts:

- name: Disable usbguard service
  service:
    name: usbguard
    enabled: false
  when: "'usbguard' in ansible_facts.packages"

- name: Stop usbguard service
  service:
    name: usbguard
    state: stopped
  when: "'usbguard' in ansible_facts.packages"
