---
- name: Install USBGuard packages
  ansible.builtin.dnf:
    name: usbguard
    state: present

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Copy reject-all USBGuard configuration file
  ansible.builtin.copy:
    content: |
      ImplicitPolicyTarget=reject
      PresentDevicePolicy=reject
      PresentControllerPolicy=reject
      InsertedDevicePolicy=reject
      IPCAllowedUsers=not_allowed
      IPCAllowedGroups=not_allowed
    dest: /etc/usbguard/usbguard-daemon.conf
    mode: '0600'
  register: daemon_config_reject
  when: usbguard_setup_policy == 'reject'

- name: Copy custom USBGuard configuration file
  ansible.builtin.copy:
    src: "{{ usbguard_setup_config_file }}"
    dest: /etc/usbguard/usbguard-daemon.conf
    mode: '0600'
  register: daemon_config_custom
  when:
    - usbguard_setup_policy == 'custom'
    - usbguard_setup_config_file is not none
    - usbguard_setup_config_file | length > 0

- name: Clear default USBGuard rules file
  ansible.builtin.copy:
    content: ''
    dest: /etc/usbguard/rules.conf
    mode: '0600'
  register: rules_config_default
  when: usbguard_setup_rules_file is none or
        usbguard_setup_rules_file | length == 0

- name: Create custom USBGuard rules file
  ansible.builtin.template:
    src: "{{ usbguard_setup_rules_file }}"
    dest: /etc/usbguard/rules.d/zz-ansible.conf
    mode: '0600'
  register: rules_config_custom
  when:
    - usbguard_setup_policy == 'custom'
    - usbguard_setup_rules_file is not none
    - usbguard_setup_rules_file | length > 0

- name: Create custom USBGuard IPC access control file
  ansible.builtin.template:
    src: "{{ usbguard_setup_ipc_access_file }}"
    dest: /etc/usbguard/IPCAccessControl.d/zz-ansible.conf
    mode: '0600'
  register: ipc_access_custom
  when:
    - usbguard_setup_ipc_access_file is not none
    - usbguard_setup_ipc_access_file | length > 0

- name: Remove unrecognized rules and IPC access control files
  vars:
    files_remove:
      - /etc/usbguard/rules.d/*
      - /etc/usbguard/IPCAccessControl.d/*
    files_remove_exclude: "{{ ['/etc/usbguard/rules.d/zz-ansible.conf'] +
                              ['/etc/usbguard/IPCAccessControl.d/zz-ansible.conf'] +
                              usbguard_setup_files_known | default([], true) }}"
  ansible.builtin.include_role:
    name: files_remove
  when: usbguard_setup_exclusive | bool

- name: Enable usbguard service
  ansible.builtin.service:
    name: usbguard
    enabled: true
  when: "'usbguard' in ansible_facts.packages"

- name: Start usbguard service
  ansible.builtin.service:
    name: usbguard
    state: started
  register: service_start
  when: "'usbguard' in ansible_facts.packages"

- name: Restart usbguard to apply configuration changes
  ansible.builtin.service:
    name: usbguard
    state: restarted
  when:
    - "'usbguard' in ansible_facts.packages"
    - service_start is not changed
    - daemon_config_reject is changed or
      daemon_config_custom is changed or
      rules_config_default is changed or
      rules_config_custom is changed or
      ipc_access_custom is changed or
      (usbguard_setup_exclusive | bool and remove_files is changed)
