---
- name: Gather needed facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Create issue directory
  ansible.builtin.file:
    path: /etc/issue.d
    state: directory
    mode: '0755'
  when:
    - issue_template is not none
    - issue_template | length > 0

- name: Create issue file
  ansible.builtin.template:
    src: "{{ issue_template }}"
    dest: /etc/issue.d/zz-ansible.issue
    mode: '0644'
  when:
    - issue_template is not none
    - issue_template | length > 0

- name: Create issue.net file
  ansible.builtin.template:
    src: "{{ issue_template }}"
    dest: /etc/issue.net
    mode: '0644'
  when:
    - issue_template is not none
    - issue_template | length > 0

- name: Create motd directory
  ansible.builtin.file:
    path: /etc/motd.d
    state: directory
    mode: '0755'
  when:
    - ansible_facts.distribution_major_version | int >= 9
    - motd_template is not none
    - motd_template | length > 0

- name: Create motd file
  vars:
    motd_path: "{{ '/etc/motd.d/zz-ansible.motd' if ansible_facts.distribution_major_version | int >= 9 else '/etc/motd' }}"
  ansible.builtin.template:
    src: "{{ motd_template }}"
    dest: "{{ motd_path }}"
    mode: '0644'
  when:
    - motd_template is not none
    - motd_template | length > 0
