---
- name: Configure load balancer
  hosts: all
  become: true
  gather_facts: true
  collections:
    - myllynen.rhel_ansible_roles
  vars:
    # haproxy template configuration
    # ...

    # keepalived template configuration
    # ...

    # Load balancer implementation
    packages_install:
      - haproxy
      - keepalived
    files_copy:
      - src: keepalived-notify-haproxy
        path: /usr/local/sbin/keepalived-notify-haproxy
        owner: root
        group: root
        mode: '0755'
    files_copy_templates:
      - src: haproxy-global.cfg.j2
        path: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
      - src: haproxy-app.cfg.j2
        path: /etc/haproxy/conf.d/app.cfg
        owner: root
        group: root
        mode: '0644'
      - src: keepalived.conf.j2
        path: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: '0644'
    #sebooleans_enable:
    #  - haproxy_connect_any
    service_state_enable:
      # keepalived will manage haproxy
      - keepalived

  roles:
    - packages_install
    - files_copy
    - sebooleans
    - service_state
    # Reload/restart services only if necessary
    - role: service_state
      vars:
        service_state_restart:
          - name: haproxy
            state: reloaded
            require: running
          - name: keepalived
            state: restarted
      when:
        - copy_templates is changed
        - start_services is not changed
