---
- name: Gather package facts
  package_facts:

- name: Remove old kernel packages
  command: dnf -C remove --oldinstallonly -y
  changed_when: true
  when: ansible_facts.packages['kernel'] | length > 1

- name: Locate NIC ifcfg configuration files
  find:
    paths: /etc/sysconfig/network-scripts
    patterns:
      - 'ifcfg-e*'
      - 'ifcfg-net*'
  register: ifcfg_files

# https://bugzilla.redhat.com/show_bug.cgi?id=2050704
- name: Fix VMware NIC configuration
  replace:
    path: "{{ item }}"
    regexp: '^\ncheck_link_down\(\) {\n return 1; \n}\n$'
    replace: ''
  register: nic_config
  loop: "{{ ifcfg_files.files | map(attribute='path') }}"

- name: Rebuild initramfs
  command: dracut -f --regenerate-all
  changed_when: true
  when: nic_config is changed

- name: Check installer log directory
  stat:
    path: /var/log/anaconda
  register: installer_logdir

- name: Locate installer leftover root files
  find:
    paths: /root
    patterns:
      - '*-ks.cfg'
      - 'install.post*.log'
  register: root_files

- name: Locate installer leftover kickstart files
  find:
    paths: /tmp
    patterns:
      - 'ks-script-*'
  register: kickstart_files
  when: installer_logdir.stat.exists

- name: Set list of installer leftover files
  set_fact:
    installer_files: "{{ (root_files.files + kickstart_files.files) | map(attribute='path') }}"
  when: installer_logdir.stat.exists

- name: Store installer leftover files
  copy:
    src: "{{ item }}"
    dest: /var/log/anaconda
    mode: '0700'
    remote_src: true
  loop: "{{ installer_files }}"
  loop_control:
    label: "{{ item }} -> /var/log/anaconda/{{ item | basename }}"
  when: installer_logdir.stat.exists

- name: Relabel stored installer files
  community.general.sefcontext:
    target: /var/log/anaconda/{{ item | basename }}
    setype: var_log_t
    state: present
  loop: "{{ installer_files }}"
  loop_control:
    label: /var/log/anaconda/{{ item | basename }}
  when:
    - "'python3-libselinux' in ansible_facts.packages"
    - installer_logdir.stat.exists

- name: Locate leftover temp files
  find:
    paths: /tmp
    patterns:
      - '.cache'
      - '.vmware-*'
      - 'foreman_*'
      - 'ks-script-*'
      - 'tmp.*'
      - 'vmware-root_*'
    file_type: any
    hidden: true
  register: leftover_files

- name: Remove all leftover files
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ (leftover_files.files + root_files.files) | map(attribute='path') }}"

- name: Reboot system
  reboot:
  when:
    - "'reboot' in system_init_final_actions"
    - inventory_hostname != 'localhost'

# Use removes: to only run on registered systems
- name: Update RHSM system facts
  command:
    cmd: subscription-manager facts --update
    removes: /var/lib/rhsm/facts/facts.json
  failed_when: false
  changed_when: true

- name: Mark system initialized
  copy:
    content: "This system was initialized by system_init on {{ '%Y-%m-%d %H:%M:%S %Z' | strftime }}.\n"
    dest: "{{ __system_init_file }}"
    mode: '0644'

- name: Log initialization message
  community.general.syslogger:
    msg: "System initialized by system_init role."
  when: "'syslog' in system_init_final_actions"
