---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Disable nscd service
  ansible.builtin.service:
    name: nscd
    enabled: false
  when:
    - "'nscd.service' in ansible_facts.services"
    - not dns_cache_enable | bool or
      dns_cache_component != 'nscd'

- name: Stop nscd service
  ansible.builtin.service:
    name: nscd
    state: stopped
  when:
    - "'nscd.service' in ansible_facts.services"
    - not dns_cache_enable | bool or
      dns_cache_component != 'nscd'

- name: Read NetworkManager DNS cache configuration
  ansible.builtin.slurp:
    src: /etc/NetworkManager/conf.d/95-dns-cache.conf
  register: current_config
  failed_when: false

- name: Update NetworkManager DNS cache configuration
  ansible.builtin.copy:
    content: |
      [main]
      #dns=
    dest: /etc/NetworkManager/conf.d/95-dns-cache.conf
    mode: '0644'
  register: nm_config
  when:
    - not dns_cache_enable | bool or
      (current_config.content is defined and
       dns_cache_component not in current_config.content | b64decode)

- name: Disable systemd-resolved service
  ansible.builtin.service:
    name: systemd-resolved
    enabled: false
  when:
    - "'systemd-resolved.service' in ansible_facts.services"
    - not dns_cache_enable | bool or
      dns_cache_component != 'systemd-resolved'

- name: Stop systemd-resolved service
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
  when:
    - "'systemd-resolved.service' in ansible_facts.services"
    - not dns_cache_enable | bool or
      dns_cache_component != 'systemd-resolved'

- name: Reload NetworkManager to apply configuration changes
  ansible.builtin.service:
    name: NetworkManager
    state: reloaded
  when: nm_config is changed
