---
- name: Disable DNS cache
  ansible.builtin.include_tasks: disable.yml

- name: Enable DNS cache using dnsmasq
  ansible.builtin.include_tasks: dnsmasq.yml
  when:
    - dns_cache_enable | bool
    - dns_cache_component == 'dnsmasq'

- name: Enable DNS cache using nscd
  ansible.builtin.include_tasks: nscd.yml
  when:
    - dns_cache_enable | bool
    - dns_cache_component == 'nscd'

- name: Enable DNS cache using systemd-resolved
  ansible.builtin.include_tasks: systemd_resolved.yml
  when:
    - dns_cache_enable | bool
    - dns_cache_component == 'systemd-resolved'
