---
- name: Install nscd package
  ansible.builtin.dnf:
    name: nscd
    state: present

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Create nscd configuration file
  ansible.builtin.template:
    src: "{{ dns_cache_nscd_config_file | default('nscd.conf.j2', true) }}"
    dest: /etc/nscd.conf
    mode: '0644'
  register: daemon_config

- name: Enable nscd service
  ansible.builtin.service:
    name: nscd
    enabled: true
  when: "'nscd' in ansible_facts.packages"

- name: Start nscd service
  ansible.builtin.service:
    name: nscd
    state: started
  register: service_start
  when: "'nscd' in ansible_facts.packages"

- name: Reload nscd to apply configuration changes
  ansible.builtin.service:
    name: nscd
    state: reloaded
  when:
    - "'nscd' in ansible_facts.packages"
    - service_start is not changed
    - daemon_config is changed
