---
- name: Install multipath packages
  ansible.builtin.dnf:
    name: device-mapper-multipath
    state: present

- name: Copy multipath configuration file
  ansible.builtin.copy:
    src: "{{ multipath_setup_config_file }}"
    dest: /etc/multipath.conf
    mode: '0600'
  register: multipath_config
  when:
    - multipath_setup_config_file is not none
    - multipath_setup_config_file | length > 0

- name: Copy multipath bindings file
  ansible.builtin.copy:
    src: "{{ multipath_setup_bindings_file }}"
    dest: /etc/multipath/bindings
    mode: '0600'
  register: multipath_bindings
  when:
    - multipath_setup_bindings_file is not none
    - multipath_setup_bindings_file | length > 0

- name: Enable multipathd service
  ansible.builtin.service:
    name: multipathd
    enabled: true
  when:
    - multipath_setup_config_file is not none
    - multipath_setup_config_file | length > 0

- name: Start multipathd service
  ansible.builtin.service:
    name: multipathd
    state: started
  register: service_start
  when:
    - not multipath_setup_reboot | bool
    - multipath_setup_config_file is not none
    - multipath_setup_config_file | length > 0

- name: Reload multipathd to apply configuration changes
  ansible.builtin.service:
    name: multipathd
    state: reloaded
  when:
    - not multipath_setup_reboot | bool
    - service_start is not changed
    - multipath_config is changed
    - multipath_bindings is changed

- name: Rebuild initramfs
  ansible.builtin.command: dracut -f --regenerate-all
  changed_when: true
  when: multipath_config is changed or
        multipath_bindings is changed

- name: Reboot system
  ansible.builtin.reboot:
  when:
    - multipath_setup_reboot | bool
    - multipath_config is changed
    - multipath_bindings is changed
