---
- name: Install multipath packages
  dnf:
    name: device-mapper-multipath
    state: present

- name: Copy multipath configuration file
  copy:
    src: "{{ multipath_setup_config_file }}"
    dest: /etc/multipath.conf
    mode: '0600'
  register: multipath_config
  when: multipath_setup_config_file

- name: Enable multipathd service
  service:
    name: multipathd
    enabled: true
  when: multipath_setup_config_file

- name: Start multipathd service
  service:
    name: multipathd
    state: started
  register: service_start
  when:
    - multipath_setup_config_file
    - not multipath_setup_reboot | bool

- name: Reload multipathd to apply configuration changes
  service:
    name: multipathd
    state: reloaded
  when:
    - not multipath_setup_reboot | bool
    - service_start is not changed
    - multipath_config is changed

- name: Rebuild initramfs
  command: dracut -f --regenerate-all
  changed_when: true
  when: multipath_config is changed

- name: Reboot system
  reboot:
  when:
    - multipath_setup_reboot | bool
    - multipath_config is changed
