---
- name: Update coredump process size configuration
  ansible.builtin.lineinfile:
    path: "{{ coredump_conf }}"
    regexp: '^(#|)ProcessSizeMax=.*'
    line: 'ProcessSizeMax=0'
  register: process_config
  when: coredump_check.stat.exists

- name: Update coredump storage configuration
  ansible.builtin.lineinfile:
    path: "{{ coredump_conf }}"
    regexp: '^(#|)Storage=.*'
    line: 'Storage=none'
  register: storage_config
  when: coredump_check.stat.exists

- name: Update default coredump limit configuration
  ansible.builtin.lineinfile:
    path: "{{ system_conf }}"
    regexp: '^(#|)DefaultLimitCORE=.*'
    line: 'DefaultLimitCORE=0:infinity'
  register: core_config
  when: system_check.stat.exists

- name: Reload systemd to apply configuration changes
  ansible.builtin.systemd:
    daemon_reload: true
  when: process_config is changed or
        storage_config is changed or
        core_config is changed

- name: Disallow suid binary coredumps
  ansible.posix.sysctl:
    name: fs.suid_dumpable
    value: '0'
    sysctl_file: /etc/sysctl.d/50-coredump.conf
    sysctl_set: true
  register: suid_config

- name: Configure system coredump pattern
  ansible.posix.sysctl:
    name: kernel.core_pattern
    value: '|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h'
    sysctl_file: /etc/sysctl.d/50-coredump.conf
    sysctl_set: true
  register: pattern_config

- name: Rebuild initramfs
  ansible.builtin.command: dracut -f --regenerate-all
  changed_when: true
  when: process_config is changed or
        storage_config is changed or
        core_config is changed or
        suid_config is changed or
        pattern_config is changed
