---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Configure Red Hat subscription using curl URL
  # noqa: command-instead-of-module
  shell: set -o pipefail ; curl {{ repository_setup_rhsm_curl_args }} | bash
  register: curl_command
  failed_when: curl_command.rc != 0 and 'already registered' not in curl_command.stderr
  changed_when: "'already registered' not in curl_command.stderr"
  when: repository_setup_rhsm_curl_args

- name: Install katello-ca-consumer-latest package
  dnf:
    name: "{{ repository_setup_rhsm_parameters.rhsm_baseurl }}/pub/katello-ca-consumer-latest.noarch.rpm"
    state: present
    disable_gpg_check: true
    validate_certs: false
    cacheonly: true
    disable_plugin:
      - product-id
      - subscription-manager
    disablerepo: '*'
  when:
    - not repository_setup_rhsm_curl_args
    - repository_setup_rhsm_parameters.rhsm_baseurl | default(false)
    - repository_setup_install_katello_rpm | bool

- name: Configure Red Hat subscription using subscription-manager
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ repository_setup_rhsm_parameters.activationkey | default(omit) }}"
    org_id: "{{ repository_setup_rhsm_parameters.org_id | default(omit) }}"
    username: "{{ repository_setup_rhsm_parameters.username | default(omit) }}"
    password: "{{ repository_setup_rhsm_parameters.password | default(omit) }}"
    auto_attach: "{{ repository_setup_rhsm_parameters.auto_attach | default(omit) }}"
    consumer_id: "{{ repository_setup_rhsm_parameters.consumer_id | default(omit) }}"
    consumer_name: "{{ repository_setup_rhsm_parameters.consumer_name | default(omit) }}"
    consumer_type: "{{ repository_setup_rhsm_parameters.consumer_type | default(omit) }}"
    environment: "{{ repository_setup_rhsm_parameters.environment | default(omit) }}"
    force_register: "{{ repository_setup_rhsm_parameters.force_register | default(omit) }}"
    pool_ids: "{{ repository_setup_rhsm_parameters.pool_ids | default(omit) }}"
    release: "{{ repository_setup_rhsm_parameters.release | default(omit) }}"
    rhsm_baseurl: "{{ repository_setup_rhsm_parameters.rhsm_baseurl | default(omit) }}"
    rhsm_repo_ca_cert: "{{ repository_setup_rhsm_parameters.rhsm_repo_ca_cert | default(omit) }}"
    server_hostname: "{{ repository_setup_rhsm_parameters.server_hostname | default(omit) }}"
    server_port: "{{ repository_setup_rhsm_parameters.server_port | default(omit) }}"
    server_insecure: "{{ repository_setup_rhsm_parameters.server_insecure | default(omit) }}"
    server_prefix: "{{ repository_setup_rhsm_parameters.server_prefix | default(omit) }}"
    server_proxy_hostname: "{{ repository_setup_rhsm_parameters.server_proxy_hostname | default(omit) }}"
    server_proxy_port: "{{ repository_setup_rhsm_parameters.server_proxy_port | default(omit) }}"
    server_proxy_user: "{{ repository_setup_rhsm_parameters.server_proxy_user | default(omit) }}"
    server_proxy_password: "{{ repository_setup_rhsm_parameters.server_proxy_password | default(omit) }}"
    syspurpose: "{{ repository_setup_rhsm_parameters.syspurpose | default(omit) }}"
  register: subscription_state
  when:
    - not repository_setup_rhsm_curl_args
    - repository_setup_rhsm_parameters.activationkey | default(false) or
      repository_setup_rhsm_parameters.username | default(false)

- name: Disable Red Hat repositories
  community.general.rhsm_repository:
    name: "{{ repository_setup_rhsm_repositories_disable }}"
    state: disabled
  register: repos_disabled
  when:
    - not repository_setup_rhsm_curl_args
    - repository_setup_rhsm_repositories_disable

- name: Enable Red Hat repositories
  community.general.rhsm_repository:
    name: "{{ repository_setup_rhsm_repositories_enable }}"
    state: enabled
    purge: "{{ repository_setup_rhsm_repositories_purge }}"
  register: repos_enabled
  when:
    - not repository_setup_rhsm_curl_args
    - repository_setup_rhsm_repositories_enable

- name: Update RHSM system facts
  command: subscription-manager facts --update
  changed_when: true
  when: repository_setup_rhsm_facts_update_always | bool or
        subscription_state is changed or
        repos_disabled is changed or
        repos_enabled is changed or
        curl_command is changed

- name: Update subscription-manager package profile update policy configuration
  vars:
    option_value: "{{ '1' if repository_setup_package_profile_on_trans | bool else '0' }}"
  lineinfile:
    path: /etc/rhsm/rhsm.conf
    regexp: '^(#|)package_profile_on_trans\s?=.*'
    line: 'package_profile_on_trans = {{ option_value }}'

- name: Enable rhsmcertd service
  service:
    name: rhsmcertd
    enabled: true

- name: Start rhsmcertd service
  service:
    name: rhsmcertd
    state: started
