---
- name: Fail if unsafe globbing in use
  ansible.builtin.fail:
    msg: "Refusing to expand unsafe globbing '*'."
  when: "'*' in files_remove | default([], true) or
         '/*' in files_remove | default([], true)"

- name: Fail if incorrect path format in use
  ansible.builtin.fail:
    msg: "Path must contain '/'."
  loop: "{{ files_remove | default([], true) + files_remove_exclude | default([], true) }}"
  when: "'/' not in item"

- name: Fail if incorrect exclude format in use
  ansible.builtin.fail:
    msg: "Globbing not supported for exclusion."
  loop: "{{ files_remove_exclude | default([], true) }}"
  when: "'*' in item or '?' in item or '[' in item"

- name: Fail if incorrect globbing pattern in use
  ansible.builtin.fail:
    msg: "Globbing only supported for the last element."
  loop: "{{ files_remove | default([], true) | map('dirname') | select('search', '\\?|\\*|\\[') }}"

- name: Locate globbed files and directories to be removed
  ansible.builtin.find:
    paths: "{{ item | dirname }}"
    patterns: "{{ item | basename }}"
    file_type: any
    hidden: true
    recurse: "{{ files_remove_recursive | bool }}"
  register: remove_globs
  loop: "{{ files_remove | select('search', '\\?|\\*|\\[') }}"

# Remove set paths from possible previous role execution
- name: Initialize list of globbed files and directories
  ansible.builtin.set_fact:
    glob_paths: []

- name: Set globbed files and directories to remove
  ansible.builtin.set_fact:
    glob_paths: "{{ glob_paths + item.files | map(attribute='path') }}"
  loop: "{{ remove_globs.results }}"
  loop_control:
    label: "{{ item.files | map(attribute='path') }}"
  when: item.files | length > 0

- name: Remove files and directories
  vars:
    plain_paths: "{{ files_remove | select | reject('search', '\\?|\\*|\\[') }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  register: remove_files
  loop: "{{ (plain_paths + glob_paths) | select }}"
  when: item not in files_remove_exclude | default([], true)
