---
- name: Remove IMA policy configuration file
  ansible.builtin.file:
    path: /etc/ima/ima-policy
    state: absent
  register: ima_policy

- name: Disable dracut integrity module
  ansible.builtin.file:
    path: /etc/dracut.conf.d/98-integrity.conf
    state: absent
  register: dracut_config

- name: Remove RPM IMA plugin package
  ansible.builtin.dnf:
    name: rpm-plugin-ima
    cacheonly: true
    state: absent

- name: Rebuild initramfs
  ansible.builtin.command: dracut -f --regenerate-all
  changed_when: true
  when: dracut_config is changed

- name: Reboot system
  ansible.builtin.reboot:
  when: ima_policy is changed or
        dracut_config is changed

- name: Check current IMA policy configuration
  check_mode: true
  ansible.builtin.lineinfile:
    path: /sys/kernel/security/ima/policy
    regexp: '^appraise.*'
    state: absent
  register: ima_policy_check
  changed_when: false

- name: Fail if IMA policy loaded
  ansible.builtin.fail:
    msg: "IMA policy still loaded, cannot proceed."
  when: ima_policy_check.found

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Check IMA security attributes on files
  ansible.builtin.command: getfattr -m - -d /usr/bin/ima-setup
  check_mode: false
  register: fattr_info
  changed_when: false
  when: "'attr' in ansible_facts.packages"

- name: Remove IMA security attributes from files
  ansible.builtin.shell: |
    set -o pipefail
    find / \( -path /proc -prune -o -path /sys -prune \) -o \( -fstype xfs -o -fstype ext4 \) -type f -print0 | \
      xargs -0 setfattr -x security.ima > /dev/null 2>&1 || :
  register: ima_attrs
  failed_when: false
  changed_when: true
  when:
    - fattr_info.stdout is defined
    - "'security.ima' in fattr_info.stdout"
