---
- name: Gather service facts
  service_facts:

- name: Fail if fapolicyd enabled
  fail:
    msg: "IMA/EVM should be setup before fapolicyd."
  when:
    - "'fapolicyd.service' in ansible_facts.services"
    - ansible_facts.services['fapolicyd.service'].state == 'enabled' or
      ansible_facts.services['fapolicyd.service'].status == 'running'

- name: Install IMA/EVM packages
  dnf:
    name:
      - attr
      - grubby
      - ima-evm-utils
      - keyutils
      - rpm-plugin-ima
    state: present

- name: Gather package facts
  package_facts:

- name: Create IMA configuration directory
  file:
    path: /etc/ima
    state: directory
    mode: '0755'

- name: Create IMA policy configuration file
  template:
    src: "{{ ima_evm_setup_policy_config_file }}"
    dest: /etc/ima/ima-policy.ansible
    mode: '0600'

# Assume IMA attributes present if ima-setup itself has it
- name: Check IMA security attributes on files
  command: getfattr -m - -d /usr/bin/ima-setup
  check_mode: false
  register: fattr_info
  changed_when: false
  when: "'attr' in ansible_facts.packages"

- name: Configure IMA
  command: /usr/bin/ima-setup --policy=/etc/ima/ima-policy.ansible --reinstall_threshold=100000
  register: ima_setup
  when:
    - fattr_info.stdout is defined
    - "'security.ima' not in fattr_info.stdout"

- name: Update IMA policy configuration file
  template:
    src: "{{ ima_evm_setup_policy_config_file }}"
    dest: /etc/ima/ima-policy
    mode: '0600'
  register: ima_policy

- name: Enable dracut integrity module
  shell: |
    diff -q /usr/share/ima/dracut-98-integrity.conf /etc/dracut.conf.d/98-integrity.conf > /dev/null 2>&1 || \
      (cp -a /usr/share/ima/dracut-98-integrity.conf /etc/dracut.conf.d/98-integrity.conf && echo changed)
  register: dracut_config
  changed_when: "'changed' in dracut_config.stdout"

- name: Rebuild initramfs
  command: dracut -f --regenerate-all
  changed_when: true
  when: dracut_config is changed

- name: Reboot system
  reboot:
  when:
    - ima_evm_setup_reboot | bool
    - ima_setup is changed or
      ima_policy is changed or
      dracut_config is changed

- name: Verify IMA security attributes on files
  command: getfattr -m - -d /usr/bin/ima-setup
  check_mode: false
  register: fattr_info
  failed_when: "'security.ima' not in fattr_info.stdout"
  changed_when: false
  when: "'attr' in ansible_facts.packages"
