#!/bin/sh

set -e

if [ "$(cat /sys/kernel/security/evm)" = "0" ]; then
  modprobe trusted
  modprobe encrypted-keys
  keyctl padd user kmk @u < /etc/keys/kmk > /dev/null
  keyctl add encrypted evm-key "load $(cat /etc/keys/evm-key)" @u > /dev/null
  echo 1 > /sys/kernel/security/evm
  sync ; echo 3 > /proc/sys/vm/drop_caches ;
fi

exit 0
