---
- name: Enable firewall
  ansible.builtin.include_tasks: enable.yml
  when:
    - firewall_enable is not none
    - firewall_enable | bool

- name: Disable firewall
  ansible.builtin.include_tasks: disable.yml
  when:
    - firewall_enable is not none
    - not firewall_enable | bool
