---
- name: Fetch files
  ansible.builtin.fetch:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    flat: "{{ item.flat | default(omit) }}"
    fail_on_missing: "{{ item.fail_on_missing | default(omit) }}"
    validate_checksum: "{{ item.validate_checksum | default(omit) }}"
  register: fetch_files
  loop: "{{ files_fetch | default([], true) }}"
  loop_control:
    label: "{{ item.src + ' -> ' + item.dest }}"
