---
- name: Install required packages
  ansible.builtin.dnf:
    name:
      - kbd
      - kbd-misc
    state: present
  register: package_install

- name: Check system keyboard configuration
  check_mode: true
  ansible.builtin.lineinfile:
    path: /etc/vconsole.conf
    regexp: '^KEYMAP=("|){{ system_keyboard }}(|")'
    state: absent
  register: keyboard_check
  changed_when: false

- name: Configure system keyboard
  ansible.builtin.command: localectl set-keymap {{ system_keyboard }}
  register: keyboard_config
  changed_when: true
  when: not keyboard_check.found

- name: Check system console font configuration
  check_mode: true
  ansible.builtin.lineinfile:
    path: /etc/vconsole.conf
    regexp: '^FONT=("|){{ system_font }}(|")'
    state: absent
  register: font_check
  changed_when: false

- name: Update system console font configuration
  ansible.builtin.replace:
    path: /etc/vconsole.conf
    regexp: '^FONT=("|).*(|")'
    replace: 'FONT={{ system_font }}'
  register: font_config
  when: not font_check.found

- name: Configure system console font
  ansible.builtin.command: setfont {{ system_font }}
  changed_when: true
  when: font_config is changed

- name: Rebuild initramfs
  ansible.builtin.command: dracut -f --regenerate-all
  changed_when: true
  when: package_install is changed or
        keyboard_config is changed or
        font_config is changed
