---
- name: Update all packages
  # noqa: package-latest
  dnf:
    name: '*'
    state: latest
    update_cache: true
  register: package_install

- name: Set package update timestamp
  set_fact:
    patch_time: "{{ '%Y-%m-%d %H:%M:%S %Z' | strftime }}"
  when: system_update_display_updates | bool or
        system_update_email_report | bool

- name: Set updated packages
  set_fact:
    package_updates: "{{ package_install.results | default([]) | sort }}"
  when:
    - system_update_display_updates | bool or
      system_update_email_report | bool

- name: Display list of updated packages
  vars:
    output_old: "{{ (package_updates | join('\n')).split('\n') }}"
    output_new: "{{ package_updates | join('\n') }}"
  debug:
    msg: "{{ output_new if ansible_version.full is version('2.11', '>=') else output_old }}"
  when:
    - system_update_display_updates | bool
    - package_updates | default(false)

- name: Install yum-utils package
  dnf:
    name: yum-utils
    state: present
  when: system_update_reboot_policy == 'when_needed'

- name: Gather package facts
  package_facts:

- name: Check need for rebooting
  check_mode: false
  command: needs-restarting --disableplugin=product-id,subscription-manager -r
  register: needs_restarting
  failed_when: false
  changed_when: false
  when:
    - "'yum-utils' in ansible_facts.packages"
    - system_update_reboot_policy == 'when_needed'

- name: Reboot system
  reboot:
  register: system_reboot
  when: (system_update_reboot_policy == 'always') or
        (system_update_reboot_policy == 'when_updated' and package_install is changed) or
        (system_update_reboot_policy == 'when_needed' and
         needs_restarting.rc is defined and
         needs_restarting.rc != 0)

- name: Send email report
  include_tasks: report.yml
  when:
    - system_update_email_report | bool
    - package_updates | default(false)
