---
- name: Gather needed facts
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution_major_version
  when: ansible_facts.distribution_major_version is not defined

- name: Install required packages
  vars:
    security_packages:
      - crypto-policies-scripts
      - "{{ 'grubby' if ansible_facts.distribution_major_version | int >= 9 else '' }}"
      - "{{ 'mokutil' if secure_boot_verify | bool else '' }}"
    selinux_packages:
      - python3-libselinux
      - python3-libsemanage
      - policycoreutils-python-utils
      - selinux-policy-targeted
      - setools-console
  dnf:
    name: "{{ security_packages | select | list + selinux_packages }}"
    state: present

- name: Gather package facts
  package_facts:

- name: Check Secure Boot state
  check_mode: false
  command: mokutil --sb-state
  register: sb_state
  failed_when: false
  changed_when: false
  when:
    - "'mokutil' in ansible_facts.packages"
    - secure_boot_verify | bool

- name: Fail if Secure Boot not enabled
  fail:
    msg: "Secure Boot not enabled."
  when:
    - "'mokutil' in ansible_facts.packages"
    - secure_boot_verify | bool
    - sb_state.stdout | regex_search("Secure?Boot enabled") is none

- name: Check kernel lockdown configuration
  vars:
    lockdown_param: "{{ 'lockdown=' + kernel_lockdown if kernel_lockdown != 'disabled' else 'lockdown' }}"
  check_mode: true
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=.*("| ){{ lockdown_param }}(=| |")'
    state: absent
  register: lockdown_check
  changed_when: false
  when: ansible_facts.distribution_major_version | int >= 9

- name: Configure kernel lockdown
  command: >
    grubby
    --update-kernel=ALL
    --remove-args=lockdown
    "{{ '--args=lockdown=' + kernel_lockdown if kernel_lockdown != 'disabled' else '' }}"
  register: lockdown_config
  changed_when: true
  when:
    - "'grubby' in ansible_facts.packages"
    - ansible_facts.distribution_major_version | int >= 9
    - (kernel_lockdown == 'disabled' and lockdown_check.found != 0) or
      (kernel_lockdown != 'disabled' and lockdown_check.found == 0)

- name: Configure SELinux state
  ansible.posix.selinux:
    policy: targeted
    state: "{{ selinux }}"
  register: selinux_config
  when: "'python3-libselinux' in ansible_facts.packages"

- name: Check current crypto policy
  check_mode: false
  command: update-crypto-policies --show
  register: current_crypto_policy
  changed_when: false
  when: "'crypto-policies-scripts' in ansible_facts.packages"

- name: Configure crypto policy
  command: update-crypto-policies --no-reload --set {{ crypto_policy }}
  register: crypto_policy_config
  changed_when: true
  when:
    - "'crypto-policies-scripts' in ansible_facts.packages"
    - current_crypto_policy.stdout != crypto_policy

- name: Check SCP configuration
  stat:
    path: /etc/ssh/disable_scp
  register: scp_state
  when: ansible_facts.distribution_major_version | int >= 9

- name: Configure SCP state
  file:
    state: "{{ 'touch' if scp_protocol_disable | bool else 'absent' }}"
    path: /etc/ssh/disable_scp
    mode: '0644'
  when:
    - ansible_facts.distribution_major_version | int >= 9
    - scp_state.stat.exists != scp_protocol_disable | bool

- name: Reboot system
  reboot:
  when: lockdown_config is changed or
        (selinux_config.reboot_required is defined and selinux_config.reboot_required) or
        crypto_policy_config is changed
