---
- name: Gather needed facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - system
  when: ansible_facts.fqdn is not defined

- name: Install required packages
  vars:
    rhc_packages:
      - rhc
      - rhc-worker-playbook
    openscap_packages:
      - scap-security-guide
    required_packages:
      "{{ ['insights-client'] +
          (rhc_packages if insights_client_rhc_enable | bool else []) +
          (openscap_packages if insights_client_scap_enable | bool else []) }}"
  ansible.builtin.dnf:
    name: "{{ required_packages | select }}"
    state: present

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Update insights-client proxy server configuration
  vars:
    proxy_set: 'proxy={{ insights_client_proxy_server }}'
    proxy_not: '#proxy='
  ansible.builtin.replace:
    path: /etc/insights-client/insights-client.conf
    regexp: '^(|#)proxy=.*'
    replace: '{{ proxy_set if insights_client_proxy_server else proxy_not }}'
  when: "'insights-client' in ansible_facts.packages"

- name: Register system to Red Hat Insights
  ansible.builtin.command:
    cmd: >
      insights-client
      --register
      --ansible-host {{ ansible_facts.fqdn }}
      --display-name {{ ansible_facts.fqdn }}
    creates: /etc/insights-client/.registered

- name: Create Red Hat Insights tags configuration file
  vars:
    tags_data: "{{ insights_client_tags | default({}, true) }}"
    tags_content: "{{ tags_data.keys() | zip(tags_data.values()) | map('join', ': ') | sort | unique | join('\n') }}"
  ansible.builtin.copy:
    content: "{{ '' if not tags_content else tags_content + '\n' }}"
    dest: /etc/insights-client/tags.yaml
    mode: '0644'
  register: tags_file
  when: "'insights-client' in ansible_facts.packages"

- name: Upload new data to Red Hat Insights
  ansible.builtin.command: insights-client --silent
  changed_when: true
  when: tags_file is changed

# https://bugzilla.redhat.com/show_bug.cgi?id=2175793
- name: Check Red Hat Subscription Management configuration
  check_mode: true
  ansible.builtin.lineinfile:
    path: /etc/rhsm/rhsm.conf
    regexp: '^hostname\s?=\s?subscription.rhsm.redhat.com'
    state: absent
  register: registration_redhat
  changed_when: false

- name: Disable rhcd service
  ansible.builtin.service:
    name: rhcd
    enabled: false
  when:
    - "'rhc' in ansible_facts.packages"
    - registration_redhat.found == 0

- name: Stop rhcd service
  ansible.builtin.service:
    name: rhcd
    state: stopped
  when:
    - "'rhc' in ansible_facts.packages"
    - registration_redhat.found == 0

- name: Enable rhcd service
  ansible.builtin.service:
    name: rhcd
    enabled: true
  when:
    - "'rhc' in ansible_facts.packages"
    - insights_client_rhc_enable | bool
    - registration_redhat.found == 1

- name: Start rhcd service
  ansible.builtin.service:
    name: rhcd
    state: started
  when:
    - "'rhc' in ansible_facts.packages"
    - insights_client_rhc_enable | bool
    - registration_redhat.found == 1
