---
- name: Create shell profile file
  ansible.builtin.template:
    src: "{{ shell_profile_file }}"
    dest: /etc/profile.d/zz-ansible.sh
    mode: '0644'
  when:
    - shell_profile_file is not none
    - shell_profile_file | length > 0
