---
- name: Install yum-utils package
  ansible.builtin.dnf:
    name: yum-utils
    state: present
  when: system_reboot_policy == 'when_needed'

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Check need for rebooting
  check_mode: false
  ansible.builtin.command: needs-restarting --disableplugin=product-id,subscription-manager -r
  register: needs_restarting
  failed_when: false
  changed_when: false
  when:
    - "'yum-utils' in ansible_facts.packages"
    - system_reboot_policy == 'when_needed'

- name: Reboot system
  ansible.builtin.reboot:
  when: (system_reboot_policy == 'always') or
        (system_reboot_policy == 'when_needed' and
         needs_restarting.rc is defined and
         needs_restarting.rc != 0)
