---
- name: Install dnf-plugins-core package
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
  when: system_reboot_policy == 'when_needed'

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Check need for rebooting
  check_mode: false
  ansible.builtin.command: dnf -C --disableplugin=product-id,subscription-manager needs-restarting -r
  register: needs_restarting
  failed_when: false
  changed_when: false
  when:
    - "'dnf-plugins-core' in ansible_facts.packages"
    - system_reboot_policy == 'when_needed'

- name: Reboot system
  ansible.builtin.reboot:
  when: (system_reboot_policy == 'always') or
        (system_reboot_policy == 'when_needed' and needs_restarting.stdout_lines is defined and
                                                   needs_restarting.stdout_lines | length > 0)
