---
- name: Remove dracut-config-rescue package
  ansible.builtin.dnf:
    name: dracut-config-rescue
    state: absent
    cacheonly: true
    disablerepo: '*'

- name: Locate rescue images
  ansible.builtin.find:
    paths:
      - /boot
      - /boot/loader/entries
    patterns: '*rescue*'
  register: rescue_images

- name: Remove rescue images
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ rescue_images.files | map(attribute='path') }}"
  register: remove_images
