---
- name: Enable rescue image
  ansible.builtin.include_tasks: enable.yml
  when: rescue_image_enable | bool

- name: Disable rescue image
  ansible.builtin.include_tasks: disable.yml
  when: not rescue_image_enable | bool
